package com.tonystevenj.heightcollector.heightcollectorstarter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

/**
 * @auther Steven J
 * @createDate 2020-09-12  15:58
 */
@Controller
//@RequestMapping(path="/demo")
public class HeightAppController {
    @Autowired// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private HeightRepository rep;


    @PostMapping(path="/add2") // Map ONLY POST Requests
    //if there added @ResponseBody, the returned message is only a word: "success" rather than success.html
//    public @ResponseBody String addNewUser (@RequestParam String email
    public String addNewUser (@RequestParam String email
            , @RequestParam Integer height) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        System.out.println(email+"+"+height);
        User n = new User();
        n.setHeight(height);
        n.setEmail(email);
        rep.save(n);
        return "success";
    }

    @PostMapping("/add")
    String creatOrderJ(@RequestBody User remote){
        rep.save(remote);
        return "success";
    }

    @GetMapping("/add3")
    public String home3(){
        return "index";

    }
    @GetMapping("/")
    public String home(){
        return "index";

    }

}
